gems:
  - bourbon
  - neat
  - bitters
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Kyle P. Feeley
description: UX Designer & Developer

# Build settings
markdown: kramdown
